services:
  api:
    image: api:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fitness
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  otel-collector:
    image: grafana/otel-lgtm:0.6.0
    ports:
      - "4317:4317"
      - "4318:4318"
      - "3000:3000"
    healthcheck:
      test: curl --silent --fail localhost:3000 || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      - GF_USERS_DEFAULT_THEME=light
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
  
  kong:
    image: kong:3.7.1-ubuntu
    container_name: kong
    volumes:
      - ./configs/kong.yaml:/config/kong.yaml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/config/kong.yaml
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8002
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_STATUS_LISTEN=0.0.0.0:8100
      - KONG_TRACING_INSTRUMENTATIONS=all
      - KONG_TRACING_SAMPLING_RATE=1.0
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8100:8100"
  
  fluentbit:
    image: fluent/fluent-bit:3.1.0
    container_name: fluentbit
    command:
      - --config=/fluent-bit/etc/fluent-bit.yaml
    volumes:
      - ./configs/fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml
